backend:
  name: github
  repo: "jlosanimalrescue/jlos-animal-rescue-site"
  branch: main

local_backend: true

media_folder: "public/images/dogs"
public_folder: "/images/dogs"

collections:
  - name: "dogs"
    label: "Dogs"
    folder: "src/data/dogs"
    create: true
    extension: "json"
    format: "json"
    identifier_field: "name"
    slug: "{{slug}}"

    fields:
      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Breed"
        name: "breed"
        widget: "string"

      - label: "Age"
        name: "age"
        widget: "string"

      - label: "Sex"
        name: "sex"
        widget: "select"
        options:
          - "Male"
          - "Female"

      - label: "Size"
        name: "size"
        widget: "select"
        options:
          - "Small"
          - "Medium"
          - "Large"

      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - "Available"
          - "Pending"
          - "Adopted"

      - label: "Featured on Homepage"
        name: "featured"
        widget: "boolean"
        default: false

      - label: "Photo"
        name: "image"
        widget: "image"
        required: false

      - label: "Description"
        name: "description"
        widget: "text"